### ISSUE TITLE
Extending memes

### ISSUE THREAD

**Issue by lukewaite** [cycomachead/hubot-meme#8]
First of all, thanks for writing this! When the old API was deprecated this became a TODO, then we found your release.

I was wondering if you'd be open to a PR that abstracted the `memeGenerator` function into it's own file. We have a few custom person-based in house memes that wouldn't warrant addition to your repo, but I would prefer to require in your `memeGenerator` rather than maintaining duplicate code.

Thanks!

**Comment by cycomachead** [comment]
> First of all, thanks for writing this! When the old API was deprecated this became a TODO, then we found your release.

Happy to help; thanks!

> I was wondering if you'd be open to a PR that abstracted the memeGenerator function into it's own file. We have a few custom person-based in house memes that wouldn't warrant addition to your repo, but I would prefer to require in your memeGenerator rather than maintaining duplicate code.

Definitely -- Ineeded, I've been thinking about something similar. Memes are (or can be) highly dependent team culture, so I can easily see wanting to customize the set of available options. (Swear words are a particular concern for some teams.)

I have two concerns, which are both solvable (depending on the path taken), but also the reason I haven't done much work into this front:
- backwards compatibility, naturally is important. So, as long as updating the repo doesn't break anything, this sounds good.
- maintaining help commands for new memes: If you're just exposing an API and being able to `require()` the package, then I don't think this would be an issue since any new script could write it's own help functions as desired.

Solving problems in an extendable way is pretty much always the way to go, so I appreciate any effort or ideas! :+1:
